### ISSUE TITLE
can you explain this calculation?

### ISSUE THREAD

**Issue by noowad93** [BinWang28/SBERT-WK-Sentence-Embedding#1]
https://github.com/BinWang28/SBERT-WK-Sentence-Embedding/blob/4eb573f07cb4841e34c0f75ccc0144315de27d3d/utils.py#L100

hello. I'm very inspired by your research.
 I would like to ask a question about above calculation.
I think this calculation is about Equation (5) from the paper.
can you explain how this works?

**Comment by noowad93** [comment]
* add
![스크린샷 2020-02-19 오후 10 14 29](https://user-images.githubusercontent.com/49383323/74837615-39845e80-5365-11ea-8a99-1518409b3c59.png)
is the blue line correct?

**Comment by BinWang28** [comment]
Hi @noowad93,

Here we want to compute the 'alignment' value by doing inner product with the vectors in the context window and then average.

Because the sum and inner product are commutable, so we made it easier in the code.

There are two small tricks:

1) In our implementation, we take the average of the vector representations (normalized) in the context window first and perform only one inner product computation, which should be identical with doing it in a sequential way.

2) Also, here we do the computation on the orthogonal basis from QR factorization which is similar to compute the inner product in the original space.

Feel free to reply if there are still some questions.

**Comment by BinWang28** [comment]
Open it again if you have further questions.

**Comment by noowad93** [comment]
thank you for answering!
