### ISSUE TITLE
Biasing Attention

### ISSUE THREAD

**Issue by g-luo** [BinWang28/SBERT-WK-Sentence-Embedding#12]
Hello! I had a few questions: 

1. I was wondering if you could bias SBERT's attention on certain words, for example if I have a sentence like "a brown dog and a cat", I would like to bias towards sentences about dogs?
2. Which model would be best to use on a news dataset? I observed binwang/bert-base-uncased worked fairly well, but I was just wondering based on your expertise. 

Thanks so much for your help!

**Comment by BinWang28** [comment]
Hi Grace,

1. To have special attention towards certain words (e.g. words in a dictionary), you may change the second part (word importance). Instead of determining the weights by variance, you can put more weights manually to words of higher interest.
2. All models are not specially designed for news datasets. I guess it is better to try a few and compare.

Hope it helps.

**Comment by g-luo** [comment]
Thank you for your quick reply! 

When you say to pick the weights manually instead of by variance, do you mean modifying what's being done [here](https://github.com/BinWang28/SBERT-WK-Sentence-Embedding/blob/889e6691cdb8f962159ad3ae02f7917c342cb34e/utils.py#L31)? I'm not quite sure where in the repo the word weights are being determined.

**Comment by BinWang28** [comment]
Hi Grace,

You can edit this part: 
https://github.com/BinWang28/SBERT-WK-Sentence-Embedding/blob/889e6691cdb8f962159ad3ae02f7917c342cb34e/utils.py#L150

var_token is the weights for different tokens in a sentence.

**Comment by g-luo** [comment]
Gotcha; thanks so much!
