### ISSUE TITLE
Whether or not the BERT listed in experimental results of STS tasks (p8, table 3) be fine-tuned?

### ISSUE THREAD

**Issue by slvher** [BinWang28/SBERT-WK-Sentence-Embedding#4]
@BinWang28 Thanks for your great work, it's very inspiring for me. 

However, for the BERT's poor performance on STS tasks (listed in table III of the SBERT-WK paper), I wonder: if the **BERT-[CLS]** and **Avg. BERT Embedding** used there are just the pre-trained models without any fine-tuning (such as with NLI data) ?  If so, and with the fact that SBERT and SBERT-WK is fine-tuned with NLI data, is it persuasive enough when comparing them together directly? (I have read the source code but just want confirm it with you to avoid misunderstanding, thanks)

**Comment by BinWang28** [comment]
@slvher 
Hi slvher,
Many thanks for asking!
(1) 
The result for BERT-CLS and Avg. are directly obtained from BERT model without any finetuning.
(2)
-Our method can be viewed as a way to aggregate/fusion information across layers from BERT-based models. So, it is generally applicable to any pre-trained BERT models.
-Therefore, if you try our method directly on the original BERT model, you would able to see the improvements on STS datasets as well. However, the result is still not satisfying because the original BERT model is not trained for STS datasets. (e.g. not good for weighted averaging)
-So, we only provide results that are using SBERT as the pre-trained model because it is a stronger baseline and provides much better performance. And we suggest using the model fine-tuned with NLI if you're working on tasks like STS datasets (also for most of the sentence level tasks.).
(3)
We will consider adding the results to the original BERT model in the future as the Appendix section. 

Hope it addresses your concerns. Feel free to ask if you have further questions.

**Comment by slvher** [comment]
@BinWang28  Make sense to me. Thank you very much for the quick response :)
